name: awesome_mxflutter
description: mxflutter demo App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 0.9.0

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_gallery_assets: 0.1.9+2
  mxflutter:
    git:
      url: http://git.code.oa.com/MXFlutter/MXFlutter.git
      ref: develop
  device_info: ^1.0.0
  mxflutter_pkg:
    git:
      url: http://git.code.oa.com/MXFlutter/mxflutter-pkg.git
  
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    #引入 mxflutter_js_bundle 下的JS Bundle 文件资源
    - mxflutter_js_bundle/

    #mxflutter app demo 使用到的图片资源
    - packages/flutter_gallery_assets/people/ali_landscape.png
    - packages/flutter_gallery_assets/logos/flutter_white/logo.png
    - packages/flutter_gallery_assets/logos/fortnightly/fortnightly_logo.png
    - packages/flutter_gallery_assets/food/butternut_squash_soup.png
    - packages/flutter_gallery_assets/food/cherry_pie.png
    - packages/flutter_gallery_assets/food/chopped_beet_leaves.png
    - packages/flutter_gallery_assets/food/fruits.png
    - packages/flutter_gallery_assets/food/pesto_pasta.png
    - packages/flutter_gallery_assets/food/roasted_chicken.png
    - packages/flutter_gallery_assets/food/spanakopita.png
    - packages/flutter_gallery_assets/food/spinach_onion_salad.png
    - packages/flutter_gallery_assets/food/icons/fish.png
    - packages/flutter_gallery_assets/food/icons/healthy.png
    - packages/flutter_gallery_assets/food/icons/main.png
    - packages/flutter_gallery_assets/food/icons/meat.png
    - packages/flutter_gallery_assets/food/icons/quick.png
    - packages/flutter_gallery_assets/food/icons/spicy.png
    - packages/flutter_gallery_assets/food/icons/veggie.png
    - packages/flutter_gallery_assets/logos/pesto/logo_small.png
    - packages/flutter_gallery_assets/products/backpack.png
    - packages/flutter_gallery_assets/products/belt.png
    - packages/flutter_gallery_assets/products/cup.png
    - packages/flutter_gallery_assets/products/deskset.png
    - packages/flutter_gallery_assets/products/dress.png
    - packages/flutter_gallery_assets/products/earrings.png
    - packages/flutter_gallery_assets/products/flatwear.png
    - packages/flutter_gallery_assets/products/hat.png
    - packages/flutter_gallery_assets/products/jacket.png
    - packages/flutter_gallery_assets/products/jumper.png
    - packages/flutter_gallery_assets/products/kitchen_quattro.png
    - packages/flutter_gallery_assets/products/napkins.png
    - packages/flutter_gallery_assets/products/planters.png
    - packages/flutter_gallery_assets/products/platter.png
    - packages/flutter_gallery_assets/products/scarf.png
    - packages/flutter_gallery_assets/products/shirt.png
    - packages/flutter_gallery_assets/products/sunnies.png
    - packages/flutter_gallery_assets/products/sweater.png
    - packages/flutter_gallery_assets/products/sweats.png
    - packages/flutter_gallery_assets/products/table.png
    - packages/flutter_gallery_assets/products/teaset.png
    - packages/flutter_gallery_assets/products/top.png
    - packages/flutter_gallery_assets/people/square/ali.png
    - packages/flutter_gallery_assets/people/square/peter.png
    - packages/flutter_gallery_assets/people/square/sandra.png
    - packages/flutter_gallery_assets/people/square/stella.png
    - packages/flutter_gallery_assets/people/square/trevor.png

  fonts:
    - family: Raleway
      fonts:
        - asset: packages/flutter_gallery_assets/fonts/raleway/Raleway-Regular.ttf
        - asset: packages/flutter_gallery_assets/fonts/raleway/Raleway-Medium.ttf
          weight: 500
        - asset: packages/flutter_gallery_assets/fonts/raleway/Raleway-SemiBold.ttf
          weight: 600


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
